### ISSUE TITLE
Detail page

### ISSUE THREAD

**Issue by zamukaev** [zamukaev/capstone-project#2]
##List of Posts

## Value Proposition

- As a user, I simply want to access a detailed view of a post, 
-  So that I can comfortably read and engage with the content.

## Description

![Image](https://user-images.githubusercontent.com/79673748/227490177-e93a4bf0-33ac-4016-b47d-f47ad5056247.png)

## Acceptance criteria
- [ ] The detail page has a button or link to return to the home page.
- [ ] The detail page shows the full content of the post.
- [ ] The detail page shows the full title of the post.
- [ ] The detail page displays an image

## Tasks

- [ ] Design and implement the layout of the detail page to display all the required information (title, content, image, ...    (publication date, and comments, if applicable)).
- [ ]  Create a "Back to Home" button or link that navigates users back to the main page.
- [ ] Make sure the layout of the detail page is responsive and adapts to different screen sizes.
- [ ] Implement route logic in the app to access the detail page under "pages/id".
- [ ] Write unit tests to verify the functionality of the detail page, the back to home button, and the route logic.
