### ISSUE TITLE
create a post page

### ISSUE THREAD

**Issue by zamukaev** [zamukaev/capstone-project#3]
## Value Proposition

- As a  User  I want to see a add post page in order to create a post

## Description

![Image](https://user-images.githubusercontent.com/79673748/227494451-dd305e06-af7f-4f6b-b285-89bc749d0e4d.png)

## Acceptance criteria
- [ ] The page has a headline "Add new Post"
- [ ] The page has a default picture 
- [ ] The page has a button "upload"
- [ ] The page has two inputs for title and text
- [ ] The page has a button "posten" wich create a post 

## Tasks

- [ ] Create the add post page
- [ ] Create the "upload" button,
- [ ] Create the "Add a post" button
- [ ] Write test
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi Muslim,

nice work! Some thoughts of mine:
- Uploading a picture might take some more effort; please consider to postpone the picture upload to a different story.
- The description does not mention what happens after I click on "posten".
  - Where am I redirected?
  - Where is the newly added post visible?
  - What happens with the form: is it reset?
