### ISSUE TITLE
Sidebar / Menu page

### ISSUE THREAD

**Issue by zamukaev** [zamukaev/capstone-project#4]
## Value Proposition

- As a  User  I want to see the sidebar in order to read it

## Description
![Image](https://user-images.githubusercontent.com/79673748/227498351-fc865e9c-b3bc-46e3-90e7-58f502e65a0a.png)
## Acceptance criteria

- [ ] The sidebar has a profile image and a background image
- [ ] The sidebar has the owner's name
- [ ] The sidebar has two links once for "about me" page once for "profile" page
- [ ] The sidebar has a button for "create a post" page

## Tasks

- [ ] Create the component sidebar
- [ ] Create the two links "profile" and "about me"
- [ ] Create the " add a post" button
- [ ] Write test
- [ ] Add to App
