### ISSUE TITLE
Header4

### ISSUE THREAD

**Issue by zamukaev** [zamukaev/capstone-project#7]
## Value Proposition

**As a** user, I want to have a header on the website with a login button, a search field, and a burger menu so that I can quickly access the necessary functions.

## Description
<img width="271" alt="Bildschirmfoto 2023-03-24 um 15 35 33" src="https://user-images.githubusercontent.com/79673748/227562520-a565ac41-21f0-4111-9737-afbb2e55ebea.png">

​

## Acceptance Criteria

- [ ] The login button should redirect to the login page.
- [ ] The search field should display results upon entering a search term and display a warning if no input is entered.
- [ ] The burger menu should contain the main menu of the app.
      ​

## Tasks

- [ ] Create the login button.
- [ ] Create the search field with corresponding functionality and warning.
- [ ] Create the burger menu.
- [ ] Write test.

**Comment by augustinanders** [comment]
Looks good to me!

Maybe you can describe better what the menu contains.
